#! /bin/sh

# Applications start with BSPWM
(SXHKD_SHELL=$(which sh) sxhkd)&
jgmenu --hide-on-startup --center &
polybar -r main &
dunst &> /dev/null &

bspc monitor -d I II III IV

bspc config border_width 3
bspc config window_gap 8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle true

bspc config normal_border_color '#353b48'
bspc config active_border_color '#718093'
bspc config focused_border_color '#dcdde1'
bspc config 'presel_feedback_color' '#2f3640'

# Application rules
bspc rule -a Chromium desktop='^1'
