#! /bin/sh

# Applications start with BSPWM
(SXHKD_SHELL=$(which sh) sxhkd)&
jgmenu --hide-on-startup --center &
polybar -r main &

bspc monitor -d I II III IV

bspc config border_width 2
bspc config window_gap 8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Application rules
bspc rule -a Chromium desktop='^1'
